export const GET_CONTACT_LIST = 'GET_CONTACT_LIST';
export const GET_CONTACT_DETAIL = 'GET_CONTACT_DETAIL';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const CLEAR_DETAIL_CONTACT = 'CLEAR_DETAIL_CONTACT';